### ISSUE TITLE
migrate project from node.js

### ISSUE THREAD

**Issue by ridhoq** [NickCarneiro/isbncollector#1]
It's not 2011 anymore

**Comment by NickCarneiro** [comment]
What would you use, Mr. code whisperer?

**Comment by ridhoq** [comment]
I was actually kinda joking. Node is aight and I've used it to some extent successfully, but I certainly think there's better technologies to use if starting a new project. Golang seems mature enough if you're willing to wade through hella docs.

But if you're trying to get a quick prototype up, then node is usually a good candidate. It just doesn't take long for it to become spaghetti like.

**Comment by NickCarneiro** [comment]
I've made a big return to node in side projects over the past few months for a few reasons.
- package game strong

npm now has more modules than any other language package manager ever. There is a module for anything you'd ever want to do. This makes it easy to ship fast.
- fun

This partly has to do with #1, but I just find node development really satisfying. The ecosystem is mature enough that all the headaches we had in 2011 have been solved. The bugs in basic tools are gone. Sure, not all the packages are A+ quality, but the big ones are battle tested. You don't have to debug the thing you're using to make the thing you want anymore.
- javascript is great for scraping

My favorite python library for scraping was PyQuery which was just aping jQuery anyway. With cheerio I can play around with jQuery snippets in the browser and then paste them directly into my code. 

To your point about spaghetti code, there are all kinds of ways to deal with callback hell. In my side projects I intentionally limit scope so I don't have to worry about that kind of thing. Plus the tooling for reliability and code quality is top notch. tape makes TDD enjoyable, gulp makes it easy to use a linter, css processors, jsx, etc. And everyone gets continuous integration for free with travis.

**Comment by ridhoq** [comment]
Yeah but npm is so dumb dude. I just recently learned that there is no smart dependency checking aka if lib a depends on lib b and lib b depends on lib a then both libs will be downloaded an extra time in their respective node_modules folders. Not that it's a huge concern for a side project but it irks me. Although that will be fixed in npm 3 apparently.

Have you considered io.js? At least that way you get some es6 sugar.

I agree with you that node is past the point of critical mass with respect to community support. I just feel like there are better technologies out there.

**Comment by ridhoq** [comment]
And if you want hipsterCred++, you should write something in Rust with me. I have been itching to write some Rust code.

**Comment by NickCarneiro** [comment]
It looks like good fun for a weekend hack session, but those systems
languages are wildly inappropriate for my one-off applications. It's not
like my choice of language is holding me back from writing web-scale
infrastructure here.

Look at my public repos: command line tools, utility libraries, web app,
and scrapers.

The biggest advantage of emerging or niche languages has nothing to do with
syntax or features. It's all about small energized communities who care
about the craft. You get a group of serious committed people for free. Look
at the Haskell subreddit. Those homies are tight.

**Comment by ridhoq** [comment]
Oh I don't think Rust is ready for "web-scale". See http://arewewebyet.com/. Just want to hack something together.

I do think Rust has that type of community and it would be cool to get in on it while its still young.

One question: are you using a data store for this project? If so, what are you using? I was looking into the SQL ORM libraries for node and narrowed it down between bookshelf.js and sequelize. Any thoughts on those or previous experience?

Btw, we should totally have a google hangout and banter about this stuff.

**Comment by NickCarneiro** [comment]
Just come to San Francisco. We have an air mattress.
